repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--allow-multiple-documents]

-   repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.1.14
    hooks:
    # Run the linter.
    - id: ruff

-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    -   id: black
        language_version: python3.9
        args:
            - "-S"
